### ISSUE TITLE
rpc

### ISSUE THREAD

**Issue by goozang-records** [rust-p2p/s-kademlia#2]
Section 4.1 references how *strong signatures* are robust against replay attacks with **nonces inside the RPC messages**. 

@dvc94ch you've built rpc stuff before, where should this live and what should this look like?

**Comment by dvc94ch** [comment]
this is handled by the transport layer. we have a set of hard coded bootstrap nodes and their public key. the transport layer starts with a handshake to authenticate the bootstrap node and establish a session key. the discovery of new nodes includes both their public key and their address/port. I think you can just assume for now that the transport is encrypted and replay proof.

**Comment by goozang-records** [comment]
ok, will make that assumption
